- cmd/nfs-subdir-external-provisioner/provisioner.go
Most controllers support both inclusterconfig and outofclusterconfig.
Normally I used nfs-subdir-external-provisioner's inclusterconfig, but I needed outofclusterconfig for special purposes.
This PR makes outofclusterconfig possible by optionally putting the `KUBECONFIG` environment variable in the deployment.
> Support for running controller outside of cluster

- README.md
- cmd/nfs-subdir-external-provisioner/provisioner.go
Hello,
This PR resolved issue #6 .
In the scope of this PR was added the ability to use metadate (name, namespace, labels, annotations) PVC field for dynamical creation the pvPath and possibility saving data on nfs-storage after deletion PV.
Example:
StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: nfs
provisioner: nfs.lgi.io/dynamic-provisioner
parameters:
onDelete: "retain"
pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.lgi.io/storage-path}"
mountOptions:
- lookupcache=pos
```
PersistentVolumeClaim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: hollow-producer
namespace: lab5a
annotations:
volume.beta.kubernetes.io/storage-class: "nfs"
nfs.lgi.io/storage-path: "hollow-export" # path which will created: /lab5a/hollow-export
spec: …
```
> Update path creation and implemented possibility save data after removing PV

- cmd/nfs-subdir-external-provisioner/provisioner.go
StorageClass supports MountOptions (PersistentVolumeSpec.MountOptions) which can be later used in provisioner when creating the PersistentVolume.
This is very helpful for users that want to apply mount options on their NFS mounts like `vers`, `rsize`, `wsize` and more.
Related to question: #24
> Enable mountOptions from StorageClass to PersistentVolume

- .github/workflows/release.yml
- Dockerfile.multiarch
- README.md
This change introduces a GitHub Workflow based pipeline. The pipeline builds Docker images for `linux/amd64`, `linux/arm64`, and `linux/arm/v7` platforms and publishes them using a multi-arch manifest under `quay.io/external_storage/nfs-subdir-external-provisioner` name attaching tags according to next rules:
1. For master branch uses `:edge` tag and pushes images to the registry.
2. For any other branch except master, uses the branch name as the tag name replacing `/`s with `-`s, and pushes to the registry.
3. For any tag matching patter `v{major}.{minor}.{patch}` creates several tags: `latest`, `{major}`, `{major}:{minor}`, `{major}:{minor}:{patch}` and pushes to the registry. For any other tag, it uses the tag's name as the image tag and pushes too. 
4. For pull requests it uses …
> Add GitHub multi-architecture pipeline

- .cloudbuild.sh
- Dockerfile
- README.md
- cloudbuild.yaml
- go.sum
- release-tools/.prow.sh
- release-tools/CONTRIBUTING.md
- release-tools/LICENSE
- release-tools/OWNERS
- release-tools/README.md
- release-tools/RELEASE.md
- release-tools/SECURITY_CONTACTS
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/build.make
- release-tools/cloudbuild.sh
- release-tools/cloudbuild.yaml
- release-tools/code-of-conduct.md
- release-tools/filter-junit.go
- release-tools/go-get-kubernetes.sh
- release-tools/prow.sh
- release-tools/travis.yml
- release-tools/update-vendor.sh
- release-tools/util.sh
- release-tools/verify-go-version.sh
- release-tools/verify-shellcheck.sh
- release-tools/verify-subtree.sh
- release-tools/verify-vendor.sh
Followed the steps listed here (https://github.com/kubernetes-csi/csi-release-tools)  
to setup automated builds via release-tools.
- add release-tools via git subtree
- update Makefile to use the release-tools/make
- add cloudbuild inks from release-tools
- update Dockerfile as expected by release tools
All the commits except  (15bc8b04232438ac9e5372bf5d5a6d1325b1db4a) are from `git add subtree`.
Verified that the following commands are working:
`make all`
`make`
`make container`
> Setup automated builds using the release-tools

- deploy/helm/Chart.yaml
**What is this PR?**
The helm chart kubeVersion is set to `>=1.9.0 <1.20.0` which exclude pre-releases i.e `1.18.0-rc` and even `1.18.0-eks`.
This PR change the semver range to include such releases since they are supported.
this solution tested by using helm's chartutil `IsCompatibleRange` method.
ref: #38
> Change the helm chart kubeVersion semver to include pre-releases

- CHANGELOG.md
- README.md
- deploy/class.yaml
- deploy/deployment-arm.yaml
- deploy/deployment.yaml
- deploy/objects/class.yaml
- deploy/objects/deployment-arm.yaml
- deploy/objects/deployment.yaml
- deploy/test-claim.yaml
The examples still uses some old `volume.beta.kubernetes.io/storage-class` annotation which replaced by `storageClassName` and this strange `fuseim.pri/ifs` provisioner name.
Those both fixed by this PR.
The changelog is not updated since `v2.0.1` and if we soon want to release `v4.0.0` then we should fill the holes in the changelog.
In this PR I will fill the missing versions in the CHANGELOG by following the changes in `git log` in the deprecated repository between the version tags until it was deprecated. Then continue to do the same from this repository log until today.
> Update examples and build updated CHANGELOG

- Makefile
we are building arm64 but arm7 is 32bit and therefore another image is required.
it worth `v4.0.1` release imo
Fixes #57
> Add arm7 to multiarch build

- cmd/nfs-subdir-external-provisioner/provisioner.go
This change brings back functionality that was present in the retired [nfs-client-provisioner](https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client) and introduced behavioral change. Having folder that includes namespace, pvc name and pv name also in archived state is beneficial and it is what always made this provisioner different from i.e. AzureFile and similar, where you have to browse and search a long time until you get to your desired archived/created folder.
> Preserve name of the PV directory name during archiving

- charts/nfs-subdir-external-provisioner/Chart.yaml
we forgot to bump the version in #56 but we modified the chart and caused [build failure](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/runs/2024265003).
> Bump helm chart to 4.0.3

- .github/workflows/helm-chart-lint.yml
As suggested by @james-d-elliott in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/61#issuecomment-790292525 we can use `ct` which is the official tool for chart testing that contains linter that can prevent mistakes like we did by merging #56 without bumping the chart version.
the action will run on PR's and will fail if the chart changed but the version match the version in the origin master branch.
> Setup chart linter as github action

- .github/workflows/helm-chart-lint.yml
- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/values.yaml
the chart linter is [failing](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/68/checks?check_run_id=2044525557) because our chart missing maintainers in the Chart.yaml and some trailing spaces.
this PR will disable this check. there are no official maintainers and the chart have enough links to the git repository if someone want to contact maintainers.
> Fix the helm chart linter test failure

- CHANGELOG.md
- README.md
- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/README.md
- charts/nfs-subdir-external-provisioner/values.yaml
- deploy/deployment.yaml
- deploy/objects/deployment.yaml
all work related to release version 4.0.1
- Add arm7 (32bit) support (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/58)
- Preserve name of the PV directory name during archiving (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/59)
> Release v4.0.1

- cmd/nfs-subdir-external-provisioner/provisioner.go
If storageClass enable pathPattern like:
`pathPattern: "${.PVC.annotations.nfs.io/storage-path}"`
but pvc without annotation would make empty `customPath` and create a pv with nfs root path.
> prevent mounting of root directory

- .github/workflows/helm-chart-lint.yml
- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/README.md
- charts/nfs-subdir-external-provisioner/templates/_helpers.tpl
- charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
- charts/nfs-subdir-external-provisioner/templates/clusterrolebinding.yaml
- charts/nfs-subdir-external-provisioner/templates/deployment.yaml
- charts/nfs-subdir-external-provisioner/templates/persistentvolume.yaml
- charts/nfs-subdir-external-provisioner/templates/persistentvolumeclaim.yaml
- charts/nfs-subdir-external-provisioner/templates/podsecuritypolicy.yaml
- charts/nfs-subdir-external-provisioner/templates/role.yaml
- charts/nfs-subdir-external-provisioner/templates/rolebinding.yaml
- charts/nfs-subdir-external-provisioner/templates/serviceaccount.yaml
- charts/nfs-subdir-external-provisioner/templates/storageclass.yaml
- charts/nfs-subdir-external-provisioner/values.yaml
Fixes #63 
Adds the ability to add custom labels to created resources 
also adds the ability to add annotations to: storage class, pod and service account.
also, there was a missing documentation of image pull secrets that was exists but missing from values.yaml and readme.
the default labels should have been from `app.kubernetes.io/` namespace and not just `name` or `release` by the best practices but it may breaks compatibility to someone and anyway `matchLabels` (selectorLabels) are immutable once created so i gave up on that.
the changes tested and are the it is upgrade-able and backward compatible.
> Helm chart labels and annotations and add missing image pull secrets in documentation

- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
- deploy/objects/clusterrole.yaml
- deploy/rbac.yaml
Fixes #70 :
1. Adds RBAC permissions to get nodes in the cluster.
2. Bumps chart version.
> PV provisioning fails when storageclass has volumeBindingMode as 'WaitForFirstConsumer'

- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/templates/_helpers.tpl
- charts/nfs-subdir-external-provisioner/templates/deployment.yaml
PR #72 adds the ability to specify labels for all objects created but it does not allow to control the deployment's pods labels which is sometimes important.
we [can't](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/72#discussion_r594247776) just use `nfs-subdir-external-provisioner.labels` because it contains version information and will force redeployment every chart upgrade. instead, we will use `nfs-subdir-external-provisioner.podLabels` which consist of `nfs-subdir-external-provisioner.selectorLabels` and user defined labels.
Fixes #63
/cc @mkilchhofer
/cc @kmova 
/assign @kmova
> Use podLabels with user defined labels in deployment pod template

- README.md
In the set up authorization section of the README replace namespace in `./deploy/deployment.yaml` as well for OpenShift deployments since it is set to the default namespace
> Update sed command for OpenShift in README.md 

- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/templates/podsecuritypolicy.yaml
Simple fix, but if you have podsecuritypolicy in your cluster, this chart doesn't work without this change.
> helm chart: allow persistentVolumeClaim in psp or pod never launches

- deploy/test-pod.yaml
Changing the images used in the test-pod to a more recent tag that also has multi-arch builds.
Previously on an arm processor the test-pod would show Failed with not much hints as to why.
Closes #131
> test: update image used by test-pod

- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/README.md
- charts/nfs-subdir-external-provisioner/templates/persistentvolume.yaml
- charts/nfs-subdir-external-provisioner/values.yaml
This Pull request adds a new value in values.yaml, `nfs.reclaimPolicy` that defines the reclaimPolicy for the main NFS persistentVolume.
Currently the reclaimPolicy is set to the same value as the one for the autogenerated StorageClass, but that is not what is wanted/needed in some use cases. See https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/128 for a further description of when we want these reclaimPolicies to differ.
Fixes: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/128
> Separate reclaimPolicies for auto-generated StorageClass and main NFS PV

- deploy/objects/clusterrolebinding.yaml
- deploy/objects/deployment.yaml
- deploy/objects/role.yaml
- deploy/objects/rolebinding.yaml
- deploy/objects/serviceaccount.yaml
`deploy/*.yaml` and `deploy/objects/*.yaml` are not matched.
`deploy/objects/*.yaml` uses `extensions/v1beta1 Deployment` and looks old, so it has updated.
> Match deploy/*.yaml and deploy/objects/*.yaml

- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/templates/deployment.yaml
- charts/nfs-subdir-external-provisioner/values.yaml
Continuing https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/105, as it appears to be abandoned. I have bumped the chart version as requested in the previous MR.
This MR adds `securityContext` and `podSecurityContext` templates to the helm chart.
(new MR to fix authorship hopefully!)
> Add securityContext options to Helm Chart, bump chart version - Related to Issue #97

- README.md
- charts/nfs-subdir-external-provisioner/Chart.yaml
- charts/nfs-subdir-external-provisioner/README.md
- deploy/class.yaml
- deploy/objects/class.yaml
- deploy/test-claim.yaml
This PR solves the inconsistency in StorageClass names in the `deploy/` directory and the helm chart, which makes it hard for new users to test their helm installation with `deploy/test-claim.yaml`.
I also added documentation about how to install multiple provisioners on a single cluster because I remember people had troubles with that in the past. 
(and a small typo...)
Related to: #118, #95, #78
Closes #164 
CC @kmova
> docs: consistent StorageClass names, multiple provisioners installation

- Makefile
as the tuple of BUILD_PLATFORM changed for csi-release-tools for
multi-arch builds, we need to   either correct the variable
in the repo or delegate that setting to csi-release-tool setting.
Ref # https://github.com/kubernetes-csi/csi-release-tools/pull/181
This is causing the test to fail as seen here:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/canary-nfs-subdir-external-provisioner-push-images/1521591446950383616
Fix # https://github.com/kubernetes/kubernetes/issues/109910
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> remove BUILD_PLATFORM variable setting from the makefile

- .cloudbuild.sh
- Makefile
Since https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/179 merged, the build platforms scheme changed (https://github.com/kubernetes-csi/csi-release-tools/commit/05c1801), and since then our build failed every time because the arguments aren't parsed correctly and causing the build to [fail](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-nfs-subdir-external-provisioner-push-images/1529885937834659840#1:build-log.txt%3A332).
now it's should be ok. 
Related to https://github.com/kubernetes/kubernetes/issues/109910
Related to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/199
> build: fix build platforms to new scheme

- Dockerfile.multiarch
since commit 656623a00ff44aeb4c9d506c0fe63e1194345306 (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/175)  the multiarch docker image cannot be built with golang 1.14 anymore.
at least 1.17 is required, but prow.sh validates golang 1.18 ([prow.sh#L89](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/release-tools/prow.sh#L89)) so we will use 1.18 from now.
i am wondering, does that mean that we need to bump go.mod version as well ([go.mod#L3](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/go.mod#L3))?
> build: build multiarch image with golang 1.18

- README.md
Changed at https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/commit/65b3ac93b6e8f621fc6b42dd1d2cb1d7a6be2b9e 
But it missed the one in README.md
> fix(docs): managed-nfs-storage -> nfs-client

- cmd/nfs-subdir-external-provisioner/provisioner.go
Hi, I reopen this PR: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/185 since the CLA signatura was not fixed.
> Fix onDelete option for subdirectories

- Dockerfile
- Dockerfile.multiarch
- go.mod
- Update multiarch build container to use golang:1.19 as the project is tested on 1.19
- Update the multiarch container to run Alpine 3.18
Updating to this version reduces the number of known vulnerabilities in the image
- Update go.mod to match the container version
> Update container version

- CHANGELOG.md
Look's like we are ready for v4.0.3, here is the changelog. 
The version can be tested with image: `quay.io/yonatankahana/nfs-subdir-external-provisioner:v4.0.3-rc2`. 
For helm use: `--set image.repository=quay.io/yonatankahana/nfs-subdir-external-provisioner,image.tag=v4.0.3-rc2`
quay.io [report](https://quay.io/repository/yonatankahana/nfs-subdir-external-provisioner/manifest/sha256:bd955a6b9b64a1c53f59cf070c592e208ec35e83a29aedd899cb10f2a2b9c684?tab=vulnerabilities) and Trivy report:
```
$ trivy image quay.io/yonatankahana/nfs-subdir-external-provisioner:v4.0.3-rc2
quay.io/yonatankahana/nfs-subdir-external-provisioner:v4.0.3-rc2 (debian 11.8)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
@kmova - let's release it
/assign @kmova
> docs: add changelog for v4.0.3
